### ISSUE TITLE
[FEATURE] Item(in List) View

### ISSUE THREAD

**Issue by ongdyub** [swsnu/swppfall2022-team14#10]
**구현하고자 하는 기능**
구현하고자 하는 기능은 무엇입니까?
List 안에 들어갈 개별 Item의 View

**위의 기능의 구현 방식**
ex) A에 B메소드 추가, 모델 추가 등...
Cocktail List를 map 해줄 Component 구현, 클릭 시에 Item Page로 Redirect

**기타**

**Comment by AlongwithKiman** [comment]
#7 과 dependancy가 있어보여 #7 에서 같이 진행해야 할 것 같습니다.
