### ISSUE TITLE
[BUG] 에러 핸들링 / 프론트 엔드 alert

### ISSUE THREAD

**Issue by nemga123** [swsnu/swppfall2022-team14#229]
**의도한 동작**
백엔드 쿼리 에러에 맞는 alert나 변경사항 제시

**실제 동작**
콘솔 로그에 에러만 뜨고 딱히 처리 X

**생각하는 원인과 수정 방법**
백엔드에서 에러를 리턴할때 정해진 코드와 같이 리턴하는 방식으로 수정

**Comment by ongdyub** [comment]
프론트의 경우 toast.ui 쓰면 예쁘게 alert가 될겁니다
