### ISSUE TITLE
[BUG] InitPage List 시 cocktailLIst가 빈 배열인 경우

### ISSUE THREAD

**Issue by ongdyub** [swsnu/swppfall2022-team14#51]
**의도한 동작**
틀은 남아있어야함

**실제 동작**
.map에서 오류가 나 렌더가 불가능

동작 재현 방식:

**생각하는 원인과 수정 방법**
수정 방식을 제대로 인지하지 못할지라도 간단히 "왜 이러한 버그가 발생하였고 어디의 문제일 것이다. 어떻게 수정해보면 좋겠다"로 작성 

**스크린샷**
없을 시 항목 삭제 가능

**Comment by AlongwithKiman** [comment]
혹시 오류 스크린샷 첨부 가능할까요?? develop branch에서 해당 오류가 없는 것 같습니다.

**Comment by AlongwithKiman** [comment]
제가 확인해봤을 때는 빈 배열이라서가 아니라 reponse.data.cocktail을 받지 않아 생긴 문제였던 것 같습니다. 관련 pr #59  확인 부탁드립니다.
